homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 46.0664
  longitude: 13.2569
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 135
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  customize:
    sensor.dark_sky_summary:
      friendly_name: "Stato"

config:
#
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
frontend:
mqtt:
  broker: localhost
  port: 8883
  client_id: HomeAssistant
  username: sergio
  password: donatella
  discovery: true
  discovery_prefix: homeassistant
# Weather prediction
# Text to speech
tts:
  - platform: google
sensor: !include sensors.yaml
group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
# Example configuration.yaml entry

  #- platform: rest
  #  resource: http://IP_ADDRESS/ENDPOINT
switch:
  - platform: mqtt
    name: "Riscaldamento"
    command_topic: "/casa/esterno/caldaia/relay"
    optimistic: false
    qos: 0
    retain: true
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Acqua Calda"
    command_topic: "/casa/esterno/caldaia/acqua"
    optimistic: false
    qos: 0
    retain: true
    payload_on: "1"
    payload_off: "0"
media_player:
  - platform: kodi
    host: 192.168.1.13
    turn_off_action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: standby
zone:
  - name: Home
    latitude: 46.1021168
    longitude: 13.205987
    radius: 100
    icon: mdi:account-multiple
  - name: Globo
    latitude: 46.0924501
    longitude: 13.2333719
    radius: 100
    icon: mdi:basket
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
